#!/bin/bash

get_iface(){
	echo -n "$(ip route show to root 192.168.1/24 src 192.168.1/24 | awk '{print $3}')"
}

net_scale(){
	local val="$1"
	local labels=("B" "KB" "MB" "GB" "TB" "PB" "EB" "ZB" "YB")
	local label_scale=0
	while [ "$(echo "$val > 2^10" | bc)" -eq 1 ]; do
		val="$(echo "scale=2; $val/2^10" | bc)"
		label_scale=$(( label_scale + 1 ))
	done
	echo "$val ${labels[$label_scale]}"
}
