#!/bin/bash

curdir="$(dirname "$(readlink -f "$0")")"

main(){
    local info
    local buf
    local devices
    local n_devices

    #turn off for non-bluetooth machines
    if ! type -v hciconfig >/dev/null 2>&1; then
        exit 0
    fi

    while :; do
        info="$(hciconfig)"

        if echo "$info" | grep "UP RUNNING" >/dev/null 2>&1; then
            n_devices="$(hcitool con | tail -n +2 | wc -l)"
            buf="${C_TITLE}%{A:$curdir/popups/bluetooth:}${MD_BLUETOOTH_CONNECTED}%{A}${C_RST} ${n_devices}"

        elif echo "$info" | grep "DOWN" >/dev/null 2>&1; then
            buf="${C_DISABLE}${MD_BLUETOOTH}${C_RST}"
        else
            buf="${C_CAUTION}${MD_BLUETOOTH_DISABLED}${C_RST}"
        fi
        echo -e "$buf"
        sleep 17m
    done
}

main $@