#!/bin/bash

# This script works best if BOTH nvidia-settings and nvidia-smi are installed. Some of the information is only available in one or the other.


curdir="$(dirname "$(readlink -f "$0")")"
. "$curdir/common/gpu"


graph(){
    local rounded=$(printf "%.0f" $(echo "scale=2;$1/10"|bc))

    case $rounded in
        0) echo -e "\u23bd";;
        [1-7]) echo -e "\u258${rounded}";;
        8) echo -e "\u2591";;
        9) echo -e "\u2588";;
        10) echo -e "${C_WARN}\u25d9${C_RST}";;
    esac
}


main() {
    if [ $NVST_INSTALLED -ne 0 ] && [ $NVSM_INSTALLED -ne 0 ]; then
        echo "Either nvidia-settings or nvidia-smi must be installed to use this (preferably both)" >&2
        exit 1
    fi

    local num="$(numgpus)"

    while :; do
        line="${C_TITLE}%{A:$curdir/popups/gpu:}${MD_VIDEOCAM}%{A}${C_RST} "
        for i in $(seq 0 $((num-1)) ); do
            line="${line}${C_TITLE}$(gpu_name $i | rev | cut -d' ' -f1 | rev)${C_RST} $(gpu_temp $i)°C ${C_TITLE}U${C_RST}$(graph $(gpu_usage_perc $i)) ${C_TITLE}M${C_RST}$(graph $(percent $(gpu_memused $i) $(gpu_memtotal $i))) ${C_TITLE}${MD_TOYS}${C_RST}$(graph $(gpu_fan_percent $i)) "
        done
        echo -e "$line"

        sleep 21
    done
}

main $@
