#!/bin/bash

curdir="$(dirname "$(readlink -f "$0")")"

. "$curdir/common/network"


net_up(){
	if [ "$#" -lt 1 ]; then
		echo "net_up requires interface name as an argument" >&2
		exit 1
	fi

	local net_state=$(</sys/class/net/$1/operstate) #whether the network is connected

	if [ "$net_state" = "up" ]; then
		return 0
	else
		return 1
	fi

}

main(){
	local interface

	while :; do
		interface="$(get_iface)"

		#print internal IP if network is running
		if net_up "$interface"; then

			#check if VPN connection is running
			if pgrep -x openvpn >/dev/null 2>&1; then
				icon="${C_TITLE}${MD_VPN_LOCK}${C_RST}"
			else
				icon="${C_TITLE}${C_WARN}${MD_SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_4_BAR}${C_RST}"
			fi

			#text="$(popup_script "network" "${icon}") $(ifconfig $NET_INTERFACE | grep inet | grep -v inet6 | awk '{print $2}')"
			text="%{A:$curdir/popups/network:}${icon}%{A} $(ifconfig $interface | grep 'inet ' | awk '{print $2}')"
		else
			text="${MD_SIGNAL_CELLULAR_NULL}"
		fi

		echo -e "$text"

		sleep 93
	done
}

main $@


