#!/bin/bash

devices="$(hcitool con | tail -n +2 | awk '{print $3}')"

info=""
for item in $devices; do
    info="${info}$(hcitool name "$item"), $(hcitool rssi "$item" | sed 's/ return value//'), $(hcitool lq "$item"), $(hcitool tpl "$item")\n"
done

conkup "$info" 5 5
