#!/bin/bash

#arrays do not seem to be exportable in bash
readonly C_CPU=("$<color CE4072>" "$<color 6AB84C>" "$<color C358B9>" "$<color BEAB45>" "$<color 7E66CC>" "$<color DD8037>" "$<color 678CCC>" "$<color CA5544>" "$<color 4EB699>" "$<color BF7096>" "$<color 5F803B>" "$<color A4773F>")
readonly threshold_busy="70"
readonly threshold_temp="48"

if [ "$1" = "q" ]; then
	cpucount="$(lscpu | grep "^CPU(s):" | awk '{print $2}')"

	#per-core percentage
	for proc in `seq 1 $cpucount`; do
		color="${C_CPU[$((proc-1))]}"
		buf="${buf}${color}$<cpu cpu${proc}>% "
	done

	#per-core temperatures
	for temp in `seq 2 7`; do
		color="${C_CPU[$((temp-2))]}"
		buf="${buf}${color}$<hwmon temp $temp>°C "
		i=$((i + 1))
	done

	#physical temp
	buf="${buf}$<color >$<hwmon temp 1>°C$<color >"

	conkup "$buf" 10 1
else
	lines=""
	for i in {1..8}; do
		lines="${lines}$<top cpu $i>    $<top name $i>    $<color 708090>($<top user $i>)$<color>\n"
	done

	conkup "$lines" 10 1
fi