#!/bin/bash

# get amount (in GiB) of memory free and used
BUF="\${color 708090}Used      Free\${color}\n"
BUF="${BUF}$<mem>   $<memeasyfree>\n\n"
BUF="${BUF}\${alignc}\${color 708090}Memory Usage\${color}\n"

lines=""
for i in {1..8}; do
	lines="${lines}$<top_mem mem $i>%    $<top_mem name $i>\n"
done

conkup "$BUF$lines" 15 1
