#!/bin/bash

curdir="$(dirname "$(readlink -f "$0")")"
. "$(dirname $curdir)/common/music"




case "$1" in
	pause)
		mocp -M ~/.config/moc -P >/dev/null 2>&1
		echo "onpause:" > "$MUSIC_FIFO"
		;;
	play)
		mocp -M ~/.config/moc -U >/dev/null 2>&1
		echo "unpause:" > "$MUSIC_FIFO"
		;;
	stop) mocp -M ~/.config/moc -s >/dev/null 2>&1 ;;
	quit)
		mocp -M ~/.config/moc -x >/dev/null 2>&1
		echo "ded:" > "$MUSIC_FIFO"
		;;
	next) mocp -M ~/.config/moc -f >/dev/null 2>&1 ;;
	up)
		if moc_running; then
			mocp -M ~/.config/moc -v +10%
		else
			pactl set-sink-volume "@DEFAULT_SINK@" +10%
		fi
		;;
	down)
		if moc_running; then
			mocp -M ~/.config/moc -v -10%
		else
			pactl set-sink-volume "@DEFAULT_SINK@" -10%
		fi
		;;
	mute) pactl set-sink-mute "@DEFAULT_SINK@" toggle ;;
	*)
		if ! moc_running; then conkup "moc not running"; exit 0; fi
		ln -sf ~/.config/moc ~/.moc
		conkup "$(mocp -M ~/.config/moc -Q "%state\n%song\n%artist\n%album")\n$<moc_curtime>/$<moc_totaltime>" 4 1
		sleep 5
		rm -rf ~/.moc
		;;
esac
