#!/bin/bash

curdir="$(dirname "$(readlink -f "$0")")"
. "$(dirname $curdir)/common/network"


NET_INTERFACE=$(get_iface)
net_state=$(</sys/class/net/$NET_INTERFACE/operstate) #whether the network is connected

if [ "$net_state" = "up" ]; then
    if pgrep -x openvpn >/dev/null 2>&1; then
        buf="$(ip route show dev $NET_INTERFACE | grep via | grep -v default | awk '{print $1}')"
    else
        buf="$(dig @resolver1.opendns.com myip.opendns.com +short)"
    fi
else
    buf="down"
fi  

conkup "\${alignc}\${color 708090}Public IP:\${color} $buf"