#!/bin/bash

curdir="$(dirname "$(readlink -f "$0")")"
. "$(dirname $curdir)/common/network"

NET_INTERFACE="$(get_iface)"

read -r rx tx <<< "$(grep " $NET_INTERFACE:" /proc/net/dev | awk '{print $2, $10}' | numfmt --to=iec --field=- --format=%4.1f )"
conkup "\${alignc}\${color 708090}Totals:\${color}\n\${color 708090}RX:\${color} $rx\n\${color 708090}TX:\${color} $tx" 10 10